In [1]:
from fetch_stock_data import collect_eval_data
import numpy as np
from stock_model_trainer import StockModelEvaluator, train_eval, StockLSTM, StockCNN

# Dummy Example
Here we will just random noise to the eval data. In practice, the predictions would be generated by a stock prediction model.

## Create a synthetic set of stock predictions

In [2]:
# normally we wouldn't look at eval data at all in training in tuning. This is a dummy example.
eval_data = collect_eval_data()
eval_data.head()

c:\Users\rkved\CS7643\CS7643-Final-Project\fetch_stock_data.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(symbols, start=start_date, end=end_date, interval=freq)
[*********************100%***********************]  5 of 5 completed

Ticker            AAPL          BA         JPM         UNH         XOM
Date
2024-11-01  221.662491  154.589996  218.318420  555.512390  109.976837
2024-11-04  220.767517  155.070007  215.223923  545.930176  113.478493
2024-11-05  222.199478  151.000000  216.898499  554.993713  113.813354
2024-11-06  221.473541  147.160004  241.938416  584.024109  115.765099
2024-11-07  226.206909  150.979996  231.479813  592.598083  115.908607

In [3]:
# preds would normally come from a deep forecasting model
preds = eval_data + np.random.normal(size=eval_data.shape)
preds.head()

Ticker            AAPL          BA         JPM         UNH         XOM
Date
2024-11-01  221.678783  154.410411  217.748897  555.850369  109.249590
2024-11-04  221.593235  154.742939  216.069729  546.914493  113.532566
2024-11-05  221.265685  150.410222  217.457696  554.653358  113.146030
2024-11-06  221.367685  144.934253  241.493717  583.724221  115.230911
2024-11-07  226.524227  151.866526  231.542645  592.290480  116.326299

## Call the StockModelEvaluator 
All we have to feed are the predictions and the function will independently access the eval dataset and return metrics

In [4]:
evaluator = StockModelEvaluator()
evaluator.eval(preds)

c:\Users\rkved\CS7643\CS7643-Final-Project\fetch_stock_data.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(symbols, start=start_date, end=end_date, interval=freq)
[*********************100%***********************]  5 of 5 completed

{'per_stock_mse': {'AAPL_MSE': 0.9273284461918659,
  'BA_MSE': 0.9571030374601146,
  'JPM_MSE': 1.0133895861255138,
  'UNH_MSE': 0.992555331664586,
  'XOM_MSE': 1.0290901816660765},
 'per_stock_smape': {'AAPL_MSE': 0.35200140003375663,
  'BA_MSE': 0.4275132571003123,
  'JPM_MSE': 0.29118906934104916,
  'UNH_MSE': 0.20764304171557568,
  'XOM_MSE': 0.7596258150694797},
 'average_smape': 0.40759451665203467}

Evaluate StockLSTM

In [5]:
preds_lstm, results_lstm, lstm_model, lstm_scaler = train_eval(
    model_class=StockLSTM,
    kwargs={
        "hidden_dim": 64
    },
    seq=60,
    epochs=100,
    lr=1e-3
)

c:\Users\rkved\CS7643\CS7643-Final-Project\fetch_stock_data.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(symbols, start=start_date, end=end_date, interval=freq)
[*********************100%***********************]  5 of 5 completed
c:\Users\rkved\CS7643\CS7643-Final-Project\fetch_stock_data.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(symbols, start=start_date, end=end_date, interval=freq)
[*********************100%***********************]  5 of 5 completed

Epoch [5/100], Loss: 0.191413
Epoch [10/100], Loss: 0.152643
Epoch [15/100], Loss: 0.113068
Epoch [20/100], Loss: 0.068912
Epoch [25/100], Loss: 0.050211
Epoch [30/100], Loss: 0.037949
Epoch [35/100], Loss: 0.033384
Epoch [40/100], Loss: 0.027402
Epoch [45/100], Loss: 0.024603
Epoch [50/100], Loss: 0.019728
Epoch [55/100], Loss: 0.017589
Epoch [60/100], Loss: 0.016440
Epoch [65/100], Loss: 0.015051
Epoch [70/100], Loss: 0.013483
Epoch [75/100], Loss: 0.012299
Epoch [80/100], Loss: 0.011507
Epoch [85/100], Loss: 0.010819
Epoch [90/100], Loss: 0.010054
Epoch [95/100], Loss: 0.009124
Epoch [100/100], Loss: 0.008119

c:\Users\rkved\CS7643\CS7643-Final-Project\fetch_stock_data.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(symbols, start=start_date, end=end_date, interval=freq)
[*********************100%***********************]  5 of 5 completed

In [6]:
results_lstm

{'per_stock_mse': {'AAPL_MSE': 334.70913568741446,
  'BA_MSE': 144.98054421082117,
  'JPM_MSE': 7680.319140661579,
  'UNH_MSE': 39086.63985141507,
  'XOM_MSE': 18.43534081021205},
 'per_stock_smape': {'AAPL_MSE': 6.166129286278726,
  'BA_MSE': 5.037035491518093,
  'JPM_MSE': 36.86315289784429,
  'UNH_MSE': 36.49532516415881,
  'XOM_MSE': 3.2308776028334907},
 'average_smape': 17.55850408852668}

Evaluate StockCNN

In [5]:
preds_cnn, results_cnn, cnn_model, cnn_scaler = train_eval(
    model_class=StockCNN,
    kwargs={
        "hidden": 64
    },
    seq=60,
    epochs=100,
    lr=1e-3
)

c:\Users\rkved\CS7643\CS7643-Final-Project\fetch_stock_data.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(symbols, start=start_date, end=end_date, interval=freq)
[*********************100%***********************]  5 of 5 completed
c:\Users\rkved\CS7643\CS7643-Final-Project\fetch_stock_data.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(symbols, start=start_date, end=end_date, interval=freq)
[*********************100%***********************]  5 of 5 completed

Epoch [5/100], Loss: 0.159693
Epoch [10/100], Loss: 0.084196
Epoch [15/100], Loss: 0.037618
Epoch [20/100], Loss: 0.028443
Epoch [25/100], Loss: 0.024048
Epoch [30/100], Loss: 0.016185
Epoch [35/100], Loss: 0.012143
Epoch [40/100], Loss: 0.009306
Epoch [45/100], Loss: 0.006659
Epoch [50/100], Loss: 0.005300
Epoch [55/100], Loss: 0.004425
Epoch [60/100], Loss: 0.003813
Epoch [65/100], Loss: 0.003472
Epoch [70/100], Loss: 0.003156
Epoch [75/100], Loss: 0.002957
Epoch [80/100], Loss: 0.002793
Epoch [85/100], Loss: 0.002655
Epoch [90/100], Loss: 0.002579
Epoch [95/100], Loss: 0.002505

c:\Users\rkved\CS7643\CS7643-Final-Project\fetch_stock_data.py:26: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(symbols, start=start_date, end=end_date, interval=freq)
[*********************100%***********************]  5 of 5 completed

Epoch [100/100], Loss: 0.002447

In [6]:
results_cnn

{'per_stock_mse': {'AAPL_MSE': 625.7003037921082,
  'BA_MSE': 1409.518341717918,
  'JPM_MSE': 1162.024663087117,
  'UNH_MSE': 21522.199176169244,
  'XOM_MSE': 128.30106920051276},
 'per_stock_smape': {'AAPL_MSE': 8.74906263912206,
  'BA_MSE': 17.18187959757387,
  'JPM_MSE': 11.782061177243971,
  'UNH_MSE': 30.02026910321679,
  'XOM_MSE': 8.7335554068234},
 'average_smape': 15.293365584796017}